version: '3'
services:
  db:
    image: mysql:8.0
    container_name: capstone2_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: school_db
      MYSQL_ROOT_PASSWORD: adminpassword
      MYSQL_PASSWORD: adminpassword
      MYSQL_USER: user
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: